### ISSUE TITLE
Value set to 0

### ISSUE THREAD

**Issue by toirl** [ShinDarth/ngx-duration-picker#2]
It want to be able to set the duration to 0 (PT0S)
I set all values in the widget to 0.
Expected behaviour: Value is set to PT0S or PT0D...
Current behavior: Value is set to null.

**Comment by ShinDarth** [comment]
Since the standard officially allow both `PT0S` and `P0D`, I put `PT0S` by default but giving the possibility to change this value (even setting it to `null`) using the `zeroValue` key in the object passed as `[options]`.

**Comment by ShinDarth** [comment]
@toirl you can Star the project if you like it
