### ISSUE TITLE
Add negative duration

### ISSUE THREAD

**Issue by toirl** [ShinDarth/ngx-duration-picker#3]
It would be nice to allow negative timeshift. At leaste the ISO8601 allows a negative notation.

**Comment by ShinDarth** [comment]
can you please link some reference about how exactly is the standard allowing the negative notation?

I can't find anything here: https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by toirl** [comment]
Yes I can't find it there too. Maybe I was misleaded because the Java documentation https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence- implies that it is possible but also says that it is **not** part of the 8601. 

Is there anything wrong with implementing it anyway?

**Comment by ShinDarth** [comment]
closing since it's not a real issue
