### ISSUE TITLE
Possibility to disable duration picker control

### ISSUE THREAD

**Issue by DerHahne** [ShinDarth/ngx-duration-picker#4]
Is it possible to disable the control? We have an issue that only an user with a special role is able to change the duration. So, if the user does not have the right permission it must be possible to make the control readonly.

One solution is to render only a <span> Tag when the permission is not give but maybe it can although be possible to disable the control.

**Comment by ShinDarth** [comment]
Done, thanks for the suggestion. It will be included in release `1.3`

**Comment by DerHahne** [comment]
Thx!!! :)

**Comment by ShinDarth** [comment]
@DerHahne you can Star the project if you like it :)

**Comment by DerHahne** [comment]
Done!
